export type DistrictChurchDirectory = {
  name: string
  churches_and_congregations: string[]
}

export const DISTRICT_CHURCHES: DistrictChurchDirectory[] = [
  {
    name: 'Distrito Norte',
    churches_and_congregations: [
      'Arica',
      'Iquique',
      'Iquique - Congregación Alto Hospicio',
      'Antofagasta, Coviefi',
      'Antofagasta - Vista Hermosa',
      'Calama - Congregación',
      'Copiapó',
      'La Serena',
      'Coquimbo',
    ],
  },
  {
    name: 'Distrito Metropolitano (Santiago)',
    churches_and_congregations: [
      'Valparaíso',
      'Viña del Mar',
      'Congregación Quilpué',
      'Villa Alemana',
      'Quillota',
      'San Antonio',
      'Melipilla',
      'Talagante',
      'Padre Hurtado',
      'Maipú - Central',
      'Maipú - Pajaritos',
      'Cerrillos',
      'Pudahuel',
      'Lo Prado',
      'Quilicura',
      'Conchalí',
      'Recoleta',
      'I Iglesia Santiago (Providencia)',
      'Las Condes',
      'La Reina',
      'Peñalolén',
      'La Florida',
      'Macul',
      'San Joaquín',
      'La Cisterna',
      'San Bernardo',
      'Congregación Lomas de Mirasur',
      'La Pintana',
      'Puente Alto',
      'San José de Maipo',
      'Congregación Puerto Aysén',
      'Coyhaique',
    ],
  },
  {
    name: 'Distrito Valle Central',
    churches_and_congregations: [
      'Rancagua',
      'Rengo',
      'San Fernando',
      'Curicó',
      'Molina',
      'Constitución',
      'I Iglesia Talca',
      'II Iglesia Talca',
      'San Javier',
      'Linares',
      'Cauquenes',
      'Parral',
      'Chillán',
      'San Carlos',
      'Bulnes',
      'Tomé',
      'Penco',
      'Hualpén, Talcahuano',
      'Talcahuano - Centro',
      'I Iglesia Concepción',
      'II Iglesia Concepción',
      'III Iglesia Concepción',
      'La Estrella - San Pedro de la Paz',
      'Chiguayante',
      'Coronel',
      'Lota',
      'Los Ángeles',
      'Angol',
      'Victoria',
      'Traiguén',
    ],
  },
  {
    name: 'Distrito Sur',
    churches_and_congregations: [
      'Temuco - Central',
      'Temuco - Amanecer',
      'Temuco - Pueblo Nuevo',
      'Padre Las Casas',
      'Lautaro',
      'Carahue',
      'Nueva Imperial',
      'Pitrufquén',
      'Gorbea',
      'Loncoche',
      'Villarrica',
      'Pucón',
      'San José de la Mariquina',
      'Congregación Paillaco Bajo',
      'Congregación Dollinco',
      'Valdivia I',
      'Valdivia II',
      'Valdivia III',
      'Congregación Calquinco',
      'Congregación Máfil',
      'Lanco',
      'Los Lagos',
      'Futrono',
      'Paillaco',
      'Pichirropulli',
      'Congregación Panguipulli',
      'La Unión',
      'Río Bueno',
      'Congregación Crucero',
      'Lago Ranco',
      'Congregación Ilihue',
      'Congregación Riñinahue',
      'Congregación Ignao',
      'Congregación Pitriuco',
      'Congregación La Junta',
      'Congregación Quillaico',
      'Osorno I',
      'Osorno II',
      'Osorno III',
      'Congregación Río Negro',
      'Congregación Rucatayo',
      'Congregación San Pablo',
      'Fresia',
      'Frutillar',
      'Llanquihue',
      'Puerto Varas',
      'Puerto Montt - Central',
      'Puerto Montt - Alerce',
      'Ancud',
      'Castro',
      'Quellón',
      'Congregación Chaitén',
      'Congregación Agua Fresca',
      'Congregación Isla Cailín',
      'Congregación Lelbun',
      'Congregación Pío Pío',
      'Congregación Chaiguao',
      'Congregación Chonchi',
      'Congregación Díaz Lira',
      'Congregación Inio',
      'Punta Arenas',
      'Puerto Natales',
    ],
  },
]

export const DISTRICT_NAMES = DISTRICT_CHURCHES.map((district) => district.name)

export function getChurchesByDistrict(districtName: string): string[] {
  const district = DISTRICT_CHURCHES.find((item) => item.name === districtName)
  return district?.churches_and_congregations ?? []
}

export function isChurchInDistrict(districtName: string, churchName: string): boolean {
  if (!districtName || !churchName) {
    return false
  }

  return getChurchesByDistrict(districtName).includes(churchName)
}
