export type DistrictChurchDirectory = {
  name: string
  churches_and_congregations: string[]
}

export const DISTRICT_CHURCHES: DistrictChurchDirectory[] = [
  {
    name: 'Distrito Norte',
    churches_and_congregations: [
      'Arica',
      'Iquique',
      'Iquique - Congregación Alto Hospicio',
      'Antofagasta, Coviefi',
      'Antofagasta - Vista Hermosa',
      'Calama - Congregación',
      'Copiapó',
      'La Serena',
      'Coquimbo',
    ],
  },
  {
    name: 'Distrito Metropolitano',
    churches_and_congregations: [
      'Valparaíso',
      'Viña del Mar',
      'Congregación Quilpué',
      'Villa Alemana',
      'Quillota',
      'San Antonio',
      'Melipilla',
      'Talagante',
      'Padre Hurtado',
      'Maipú',
      'Cerrillos',
      'Pudahuel',
      'Lo Prado',
      'Quilicura',
      'Conchalí',
      'Rancagua',
      'Reñaca',
      'Recoleta',
      'I Iglesia Santiago (Providencia)',
      'Las Condes',
      'La Reina',
      'Peñalolén',
      'Ñuñoa',
      'La Florida',
      'Macul',
      'San Joaquín',
      'La Cisterna',
      'San Bernardo',
      'Congregación Lomas de Mirasur',
      'La Pintana',
      'Puente Alto',
      'Congregación Puerto Aysén',
      'Congregación Rengo',
      'Congregación Copequén',
      'Coyhaique',
    ],
  },
  {
    name: 'Distrito Valle Central',
    churches_and_congregations: [
      'San Fernando',
      'Curicó',
      'Molina',
      'Constitución',
      'I Iglesia Talca',
      'II Iglesia Talca',
      'San Javier',
      'Linares',
      'Cauquenes',
      'Parral',
      'Chillán',
      'San Carlos',
      'Bulnes',
      'Tomé',
      'Penco',
      'Hualpén, Talcahuano',
      'Talcahuano - Centro',
      'I Iglesia Concepción',
      'II Iglesia Concepción',
      'III Iglesia Concepción',
      'La Estrella - San Pedro de la Paz',
      'Chiguayante',
      'Coronel',
      'Lota',
      'Los Ángeles',
      'Angol',
      'Victoria',
      'Traiguén',
    ],
  },
  {
    name: 'Distrito Aracaunía',
    churches_and_congregations: [
      'Congregación Nacimiento',
      'Almagro - Los Ángeles',
      'Congregación El Peral',
      'Galilea - Los Ángeles',
      'Congregación Laja',
      'Collipulli',
      'Congregación Mulchén',
      'Congregación Pobl. Miguel Zerené',
      'Angol',
      'Congregación Chacaico',
      'Arauco',
      'I Iglesia Lebu',
      'Congregación Pehuén',
      'Congregación Isla Mocha',
      'II Iglesia Lebu',
      'Congregación Cornelio Saavedra',
      'Congregación Santa Rosa',
      'Los Álamos',
      'Congregación Curanilahue',
      'Cañete',
      'Congregación Cerro Alto',
      'Contulmo',
      'Purén',
      'Congregación Los Sauces',
      'Traiguén',
      'Congregación Lumaco',
      'Congregación Quetrahue',
      'Victoria I',
      'Congregación Reducción Contreras',
      'Congregación Queipul',
      'Victoria II',
      'Congregación Púa',
      'Congregación El Salto',
      'Curacautín',
      'Lautaro',
      'Congregación Los Temos',
      'Lautaro - Rural',
      'Congregación Agua Fría',
      'Congregación Vega Catricura',
      'I ACYM Temuco Centro',
      'Congregación Monteverde',
      'Congregación Loncoche Plom',
      'Congregación Trovolhue / Comuna Carahue',
      'Congregación Alto Yupehue',
      'Congregación Labranza',
      'Congregación Fundo El Carmen',
      'II Iglesia Temuco',
      'Congregación Chivilcán',
      'III Iglesia Temuco',
      'IV Iglesia Temuco',
      'Congregación Varones Sector Niágara',
      'Iglesia Pueblo Nuevo - Temuco',
      'Villa Los Lagos - Temuco',
      'Congregación Allipén',
      'Villa Valparaíso - Temuco',
      'Congregaciones Pichico y Lleupeco',
      'Congregación Conunhueno',
      'Villa Los Sauces - Temuco',
      'Amanecer - Temuco',
      'Temuco Poniente',
      'Congregación Padre Las Casas',
      'Congregación Maquehue Buen Samaritano (Chapod)',
      'Carahue',
      'Quepe',
      'Cunco',
      'Congregación Curacalco',
      'Congregación Freire',
      'Congregación Folilco',
      'Congregación Coipúe y Pitrufquén',
      'Villarrica',
      'Congregación Lican Ray',
      'Congregación Manhue',
      'Congregación Quinta Faja',
      'Congregación Huellanto',
      'Congregación Conquil',
      'Congregación Huiscapi',
      'Cudico',
      'Congregación Curilelfu',
      'Congregación Liquiñe',
      'Congregación Cachín',
      'Pucón',
      'Congregación Catripulli',
      'Congregación Quelhue',
      'Congregación Curarrehue',
      'Congregación Maichín',
      'Loncoche',
      'Congregación Muquén',
      'Congregación Cheignal Mapu',
      'Congregación Pencolleufu',
    ],
  },
  {
    name: 'Distrito Sur',
    churches_and_congregations: [
      'San José de la Mariquina',
      'Congregación Paillaco Bajo',
      'Congregación Dollinco',
      'Valdivia I',
      'Valdivia II',
      'Valdivia III',
      'Congregación Calquinco',
      'Congregación Máfil',
      'Lanco',
      'Los Lagos',
      'Futrono',
      'Paillaco',
      'Pichirropulli',
      'Congregación Panguipulli',
      'La Unión',
      'Río Bueno',
      'Congregación Crucero',
      'Lago Ranco',
      'Casma',
      'Congregación Ilihue',
      'Congregación Riñinahue',
      'Congregación Ignao',
      'Congregación Pitriuco',
      'Congregación La Junta',
      'Congregación Quillaico',
      'Osorno I',
      'Osorno II',
      'Osorno III',
      'Osorno IV',
      'Osorno V',
      'Congregación Río Negro',
      'Congregación Rucatayo',
      'Congregación San Pablo',
      'Congregación Entre Lagos',
      'Fresia',
      'Frutillar',
      'Llanquihue',
      'Puerto Varas',
      'Puerto Montt I',
      'Puerto Montt II - Alerce',
      'Congregación Alerce',
      'Ancud',
      'Castro',
      'Coyhaique I',
      'Coyhaique II',
      'Quellón',
      'Congregación Chaitén',
      'Congregación Agua Fresca',
      'Congregación Isla Cailín',
      'Congregación Lelbun',
      'Congregación Pío Pío',
      'Congregación Chaiguao',
      'Congregación Chonchi',
      'Congregación Díaz Lira',
      'Congregación Balmaceda',
      'Chile Chico',
      'Congregación Puerto Ibañez',
      'Congregación Inio',
      'Punta Arenas I',
      'Punta Arenas II',
      'Puerto Natales',
      'Purranque',
      'Puerto Aysén',
      'Plantación Iglesia Queilen',
      'Mirasol',
    ],
  },
]

export const DISTRICT_NAMES = DISTRICT_CHURCHES.map((district) => district.name)

export function getChurchesByDistrict(districtName: string): string[] {
  const district = DISTRICT_CHURCHES.find((item) => item.name === districtName)
  return district?.churches_and_congregations ?? []
}

export function isChurchInDistrict(districtName: string, churchName: string): boolean {
  if (!districtName || !churchName) {
    return false
  }

  return getChurchesByDistrict(districtName).includes(churchName)
}
